### ISSUE TITLE
Let's default to passwordless authentication

### ISSUE THREAD

**Issue by dsernst** [Crowdocracy/liquid-api#6]
I'm strongly in favor of [passwordless authentication](http://passwordless.org). **No passwords, just send users an email with a link** that authenticates via a one-time token. When they click it, store an auth token to their device for a certain amount of time.

A passwordless system can be strictly more secure than a traditional password system:
- Developers already need to build and maintain a similar level of infrastructure for a Reset Password feature compared with a passwordless system, and then more on top of that (passwords in db + bcrypt + salting) to support passwords.
- Asking users to create new passwords is often insecure: 
   1. they choose a short one that's easy to brute force
   2. they re-use across multiple services
- Where they choose to store their passwords introduces vulnerability: post-it notes, unencrypted files on their computers
- It lets the user concentrate on securing their email (which was already necessary), instead of each and every password
- It's more obvious to the user that someone's trying to break into their account than if someone learns their password and logs in directly
- Most users end up forgetting their passwords often, and already depend upon the Reset Password feature. So they're basically going passwordless anyway, but still being asked to create a new password each time, guilted for not remembering it, and exposed to the same security vulnerabilities if someone does learn it.

Slack does this already. They call it a "Magic Link". They're [celebrated for it on "Great UX Design" blogs](http://littlebigdetails.com/post/86569044847/slack-after-changing-your-password-slack-lets). I've always been super happy with their system here.

Here's an example of Express middleware to implement this: [passwordless.net](https://passwordless.net/). Auth0 has [a library to implement](https://auth0.com/passwordless) too.

**Comment by dsernst** [comment]
I'm closing this because it's been two weeks and no one has commented against.

Feel free to comment if you want to re-visit.

**Comment by jaredscheib** [comment]
This sounds like a good first step to me, which sounds like it shouldn't interrupt us transitioning to a password-based system if for any reason we so decided. Let's go ahead with it!
